name: Deploy DuocPhuMinh

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main
    steps:
     
      - uses: actions/checkout@v1
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          source: "."
          target: "/var/www/duocphuminh"

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            cd /var/www/duocphuminh
            npm install
            yarn install-de
            touch backend/.env
            echo "${{ vars.BACKEND_ENV }}" > backend/.env
            npm run start
